version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal
  publish_nuget: true
artifacts:
  - path: '**\*.nupkg'
cache:
  - packages -> **\packages.config
build_script:
- cmd: >-
    dotnet restore

    dotnet build
#branches:
#  only:
#  - master
#skip_non_tags: true
