version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal
cache:
  - packages -> **\packages.config
build_script:
- cmd: >-
    dotnet restore

    dotnet build