version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal
  publish_nuget: true
artifacts:
  - path: '**\*.nupkg'
cache:
  - packages -> **\packages.config
build_script:
- cmd: >-
    dotnet restore

    dotnet build
deploy:
  provider: NuGet
  api_key:
    secure: 8kmUa5BLDm7Z6Jc4d1ZkBPnFvZ/KFIicVZncU8vTru945YrHKSSKoHI4EG/aDzMC
  skip_symbols: false
  artifact: /.*\.nupkg/

branches:
  only:
  - master
skip_non_tags: true
